### ISSUE TITLE
Require setting options(rights_holder=<some value>) for methods that create/update sysmeta

### ISSUE THREAD

**Issue by sbpcs59** [DataONEorg/rdataone#100]
The R client can't currently decode authentication tokens (no R package or base function to do this) , which would be the first place to get a value for rightsHolder (use subject field) to use for a sysmeta object that will be uploaded to DataONE.

So, if options("rights_holder") isn't set by the user, I don't see any option but to throw a warning()
telling the user to set it. This is far better than having the user create sysmeta objects
that have a blank rightsHolder, allowing them to upload but can't update, archive, etc.

This should be done for create(), updateSystemMetadata(), etc.

**Comment by cboettig** [comment]
@sbpcs59 Peter, can you give a bit more information about what would be needed to decode these tokens? Are there good existing C libraries that do what you need?  If this is the kind of thing that would be of general value for the R infrastructure maybe rOpenSci can be of some help knocking something out.

**Comment by sbpcs59** [comment]
@cboettig Carl - what's needed is the ability to decode the token and extract the "userId" field from
the payload section of the token.  These tokens are JSON Web Tokens that are base64url
encoded. There is a C library available from http://jwt.io (repo at https://github.com/benmcollins/libjwt)
that does everything needed. I haven't yet found any libraries available from MacPorts, ubuntu repos, etc.
that have JWT processing. Any assistance from rOpenSci would be greatly appreciated!

**Comment by mbjones** [comment]
@cboettig We discussed making yet another R package to wrap the jwt.io library in R -- it would be pretty simple because its a small library with only a few functions, but due to timing we were reluctant to embark on that path.  Have you heard of others needing to use JWT tokens for infrastructure?

**Comment by sbpcs59** [comment]
@cboettig @mbjones A quick and dirty solution for the immediate problem is:

```
library(base64enc)
library(jsonlite)
authToken <- "<paste auth token here>"
payload <- unlist(strsplit(authToken, "\\."))[[2]]
payloadRaw <- base64decode(payload)
payloadChar <- rawToChar(payloadRaw)
tokenInfo <- fromJSON(payloadChar)
tokenInfo[['issuedAt']]
tokenInfo[['sub']]
tokenInfo[['ttl']]
```
This just decodes the payload and extracts the needed info, but isn't general purpose.

So, for the dataone functions that write  if the user hasn't specified "options(rights_holder=<some userid>)" then the 'sub' field value from the token (or certificate) will be used.

**Comment by sbpcs59** [comment]
MNode::create(), MNode::update(), MNode::updateSystemMetadata() now inspect the sysmeta@submitter and sysmeta@rightsHolder and sets them appropriately if not set:

- if sysmeta@submitter not set then set to authentication subject
- if sysmeta@rightsHolder not set then set to sysmeta@submitter

Also, when a proper R package for handling JWTs is available, that will be used if necessary,
but for now the approach shown above will be used.
