### ISSUE TITLE
Need to set sysmeta@authoritativeMemberNode on create(), update()

### ISSUE THREAD

**Issue by sbpcs59** [DataONEorg/rdataone#103]
It appears that DataONE doesn't set the system metadata authoritativeMemberNode field if the
corresponding element in the system metadata xml isn't set when it is submitted during create().
The result of this is that the newly created object in DataONE cannot be updated, nor can it's
sysmeta be updated.
Therefore MNode::create() and update() should set this field for system metadata if it is not
already set. As the 'originMemberNode' doesn't need to be set, authoritativeMemberNode should
be set to the member node id for the node that is creating the object, if it is not already set.

**Comment by mbjones** [comment]
@sbpcs59 yes, I think this would be a MN responsibility, not DataONE, as now MNs are the authoritative source of system metadata.  Best thing is for us to always set both rightsHolder and authoritativeMemberNode in our client tools.  If this is a bug, its a bug in Metacat for not checking and setting that value if it is missing when it processes a create() or update() request. Let's discuss with @leinfelder and @csjx and see if that makes sense as a ticket for metacat.

**Comment by sbpcs59** [comment]
MNode.create(), update() have been changed to set sysmeta@authoritativeMemberNode to the
node id of the node the request is being submitted to (which is the originMemberNode) (change made in commit 56b002f07eb89a4d3c0fde5a2edd33780c4c69de). A bug has been logged against metacat that describes the behaviour described above: https://projects.ecoinformatics.org/ecoinfo/issues/6938
