### ISSUE TITLE
Ensure that docs for all methods have examples

### ISSUE THREAD

**Issue by sbpcs59** [DataONEorg/rdataone#106]
Review the Roxygen docs for all methods and ensure that they have examples, when
appropriate.

**Comment by mbjones** [comment]
@sbpcs59 Some of the recent examples that were checked in have errors under R CMD check, and so should probably be enclosed in `dontrun` blocks.  See, for example, the examples in `MNode::create()` that fail.  In general, we probably should enclose most examples that require network access in `dontrun`.

**Comment by sbpcs59** [comment]
As of commit 8fc8ce4f68f834a5e1f7d88828a6b170581cc068, all methods in CertificateManager.R, AuthenticationManager.R, D1Node.R, MNode.R, CNode.R, D1Client.R have examples included.
