### ISSUE TITLE
Need to add "dataone-deprecated" to dataone help

### ISSUE THREAD

**Issue by sbpcs59** [DataONEorg/rdataone#107]
When calling a deprecated function, i.e. D1Object, the following message is printed

```
Warning message:
'.local' is deprecated.
Use 'DataObject' instead.
See help("Deprecated") and help("dataone-deprecated"). 
```

So we need to describe our deprecated functions in 'dataone-deprecated'

**Comment by mbjones** [comment]
Also note -- if you deprecate the Generic function rather than the implementation, then the message will be "'realMethodName' is deprecated." rather than '.local'.  See csv.convert for example.

**Comment by sbpcs59** [comment]
'dataone-deprecated' docs added in commit ce110c41a1ef30937d4d1cb0df3fda1bd0444424
