### ISSUE TITLE
deprecate getMN and getCN from D1Client class

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/rdataone#11]
D1Client.getCN() and D1Client.getMN() return Java object refs to corresponding java classes.  These have now been replaced with CNode and MNode S4 classes, and so should be deprecated.  Investigate what code might use these methods and refactor those as well.

**Comment by mbjones** [comment]
Rewrote these methods to return the R CNode and MNode instances.  Still need to find any code that calls these methods and ensure they still work.

**Comment by sbpcs59** [comment]
Added call to .Deprecated in commit 521e3aa1eb20d48077087e6e4e8f3a030e6af2bd
