### ISSUE TITLE
resourceMap and isDocumentedBy fields not indexed for data object

### ISSUE THREAD

**Issue by lauren-walker** [DataONEorg/rdataone#114]
I found an example where the resourceMap and isDocumentedBy fields are not indexed even though those relationships are (at quick glance) asserted in the .rdf resource map.

Data object: https://cn-sandbox-2.test.dataone.org/cn/v2/query/solr/?q=id:%22urn:uuid:695fdf2f-9361-4eac-a693-b4c9bc40f96f%22&fl=*

Its resource map: http://cn-sandbox-2.test.dataone.org/cn/v2/resolve/urn:uuid:1766ab73-09a1-4f7a-a0cd-34cc5729e110

**Comment by sbpcs59** [comment]
This was a bug in the recordr package and was fixed in commit 0bc3810a1e7465ebd6151de3a2f6d1effb8e9c17
