### ISSUE TITLE
Deprecated EMLParser, AbstractTableDescriber class and methods

### ISSUE THREAD

**Issue by sbpcs59** [DataONEorg/rdataone#117]
This functionality will be deprecated in v2.0 and should be moved to another R package.

**Comment by sbpcs59** [comment]
Not sure how to deprecate these, as we don't have any replacements to 
recommend.

**Comment by mbjones** [comment]
@sbpcs59 How about recommending the EML package, and its parsing functions?

**Comment by sbpcs59** [comment]
@mbjones The only problem is that the EML package is not on CRAN yet, so if that's 
acceptable, I'd say yes.

**Comment by sbpcs59** [comment]
In order to deprecated these, roxygen tags have to be added to the source for AbstractTableDescriber.R
and EMLParser.R, as these functions were exported in a manually edited DESCRIPTION file
in version 1.0.0

**Comment by sbpcs59** [comment]
Changed in commit b4fd0719696100c6222d00ff82311f098be55808
