### ISSUE TITLE
uploadDataObject doesn't upload DataObject@data

### ISSUE THREAD

**Issue by sbpcs59** [DataONEorg/rdataone#122]
A datapackage:DataObject can be either initialized with a 'raw' object (dataobj=) or
a filename (filename=). If the object is initialized with a raw object, then uploadDataObject
does not upload this item as dataone::create() does not allow for uploading raw objects yet.

Should this be fixed now, or after dataone::create() allows the "file" argument as a textConnection?

**Comment by mbjones** [comment]
@sbpcs59 For now, it seems best to just serialize the `raw` object to disk in a temp file, and then pass that temp file on as the file argument (and then clean it up afterwards).

**Comment by sbpcs59** [comment]
Fix implemented in commit 94a6cd99e144030396e155e7d9090aa76c085b4b, and tests added in commit
6378da1472b5f6f02a693bb5652fca4640e45136
