### ISSUE TITLE
Mark CNode::setObsoletedBy as Defunct

### ISSUE THREAD

**Issue by sbpcs59** [DataONEorg/rdataone#123]
The DataONE service CNCore.setObsoletedBy() no longer accepts client requests and returns the
following error:
```
Error obsoleting urn:uuid:770fa166-c472-426c-b4be-095c8aaf1cc1: The Coordinating Node is not authorized to make systemMetadata changes on this object. Please make changes directly on the authoritative Member Node.
```
So mark the R client method CNode::setObsoletedBy as defunct and superceded by 
MNode::updateObject()

**Comment by sbpcs59** [comment]
Changed in commit 47987ab5af7645b00058b8bf54f4bb1401756bb6

**Comment by taojing2002** [comment]
Hi, Peter:

In DataONE v2 nodes (CN and MN), the authority of the system metadata is 
shifted from the CN to the MN. Instead of calling CN.setOboletedBy 
method, you have to call the MN.updateSystemMetadata against its 
authoritative member node.

**Comment by sbpcs59** [comment]
@taojing2002 MN.updateSystemMetadata can perform the same task as CN.setObsoletedBy, but you
have to update both obsoleted and obsoletes sysmeta, so it's easy to break the obsolescence chain,
as I did with these two pids (no obsoletedBy):
```
https://mn-stage-ucsb-2.test.dataone.org/knb/d1/mn/v2/meta/urn:uuid:59a672ab-edbf-49ca-8f3a-ed7c343915c1
https://cn-stage.test.dataone.org/cn/v2/meta/urn:uuid:0ac3b074-2174-4f66-b71a-ac036765d6ab
```
I haven't tried other ways to corrupt the chain, i.e. (a obsoletes b; b obsoleted by c). 

So I'm recommending to users that they use the R client MNode.update (MNStorage.update) for
obsoleting objects, which doesn't have the granularity of MNStorage.updateSystemMetadata, but 
is probably much safer. What are your thoughts on this @vdave ?

(I'm assuming that MNStorage.update does obsolescence chain consistency checks (which I haven't tested, but I will!). 

P.S. Seems like MNStorage.setObsoletedBy() would be a good API to have, and to make the 
obsoletes, obsoleted fields in sysmeta non editable by MNStoreage.updateSystemMetadata.

**Comment by sbpcs59** [comment]
CNode.setObsoletedBy marked as defunct in commit 47987ab5af7645b00058b8bf54f4bb1401756bb6
