### ISSUE TITLE
Prevent message "No encoding supplied: defaulting to UTF-8."

### ISSUE THREAD

**Issue by sbpcs59** [DataONEorg/rdataone#128]
Most methods that call DataONE services call httr::content(response, as="text") which requires a character encoding to be specified, otherwise a message is printed. Specify UTF-8 as the
encoding scheme.

**Comment by mbjones** [comment]
That's probably the best default, but not all content in our network is UTF-8.  It would be better to use metadata about the content to determine the character encoding to be used -- setting it universally to UTF-8 will lead to at least some errors.

**Comment by sbpcs59** [comment]
The problem only occurs for services that expect an xml response (DataONE service response.
Metacat doesn't provide this, which it probably should (see https://projects.ecoinformatics.org/ecoinfo/issues/6959)

For these services, the fix is to inspect the http response for the charset, i..e. "Content-Type: text/xml;charset=UTF-8", and use it if specified, to tell httr::content() how to convert to text.
If not specified, then assume "UTF-8".

This change was made in commit 1b29dc4ed71e779abe6011e99b4750bb384fe101

**Comment by keithgw** [comment]
You can also wrap the content function in `suppressMessages`
