### ISSUE TITLE
Error: length(agent) == 1 is not TRUE when creating an MNode before loading package

### ISSUE THREAD

**Issue by amoeba** [DataONEorg/rdataone#129]
Since I'm using this package in my own package, my calls to its functions are made using the prefix syntax `dataone::FUN` instead of calling `FUN()` directly.

I noticed a strange error when I run `dataone::MNode("some mn url")`:

```{r}
> dataone::MNode("https://dev.nceas.ucsb.edu/knb/d1/mn/v2")
Error: length(agent) == 1 is not TRUE
```

If I load the dataone package and instantiate an MNode the 'normal' way I do not receive an error and get a valid MNode instance:

```{r}
> library(dataone)
> MNode("https://dev.nceas.ucsb.edu/knb/d1/mn/v2")
```

Is this something to do with classes? I can run `dataone::create()` this way with no errors.

**Comment by sbpcs59** [comment]
@amoeba This error occurs because the dataone namespace is not loaded, so the dataone
function get_user_agent(), that isn't qualified, isn't available, i.e.:

```
detach("package:dataone", unload=TRUE)
dataone::MNode("https://dev.nceas.ucsb.edu/knb/d1/mn/v2")
 
 Error: length(agent) == 1 is not TRUE 
```

It's interesting that you can access a package function that hasn't been loaded, but I'm
going to assert that you need to load the package with either 'library()', 'require()', (or loadNamespace()?)
in order to use the package properly.

**Comment by cboettig** [comment]
@amoeba I think you are probably missing the `ImportMethodsFrom` declaration in your namespace?  e.g. see http://r-pkgs.had.co.nz/namespace.html#imports .  Certainly explicit `library()` or `require()` calls should not be used in @amoeba 's case of writing another package.  Haven't tested this though.  

Reminding interactive users to use `library()` or `loadNamespace()` sounds good though.

**Comment by sbpcs59** [comment]
@cboettig Yes, calling `library()` or `require()` in a package is not advised. I'm still a little sleepy this morning I guess.

**Comment by amoeba** [comment]
Thanks @cboettig and @sbpcs59.

@sbpcs59 is this a change you want to make to the package or should I make a proper work-around in my package?

**Comment by amoeba** [comment]
Did some sleuthing with @mbjones. It looks like this might be a problem with `get_user_agent` in `auth_request.R` returning NULL in a special case. @sbpcs59 hit me up on IRC whenever and we can chat about this.
