### ISSUE TITLE
Release prep and issues

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/rdataone#133]
In checking the package for release, I found the following issues crop up.  Use this ticket to track release issues across platforms until we are ready to push to cran.

- [x] Package installs java files; need to remove these
- [x] Need to update cran-comments.md with additional platforms
- [x] Need to update NEWS with more detail about what is in the 2.0.0 release
- [x] Need to deal with the PKIPlus suggest
- [x] Register the DOI to fix the link

The release() output shows the following:

```R
* checking CRAN incoming feasibility ... NOTE
Maintainer: ‘Matthew B. Jones <jones@nceas.ucsb.edu>’
New submission

Package was archived on CRAN

Possibly mis-spelled words in DESCRIPTION:
  DataONE (4:27, 18:9)

CRAN repository db overrides:
  X-CRAN-Comment: Archived on 2014-08-29 as dataonelibs was.

Strong dependencies not in mainstream repositories:
  datapackage

Suggests or Enhances not in mainstream repositories:
  PKIplus

Package installs .java files.
Found the following (possibly) invalid URLs:
  URL: http://doi.org/10.5063/F1M61H5X
    From: README.md
    Status: 404
    Message: Not Found
```

**Comment by mbjones** [comment]
Removed HelloWorld java file.

**Comment by sbpcs59** [comment]
All tests are passing on all listed platforms. Not listed however is R-devel on win.builder. For some
reason, this build can't find datapackage and PKIplus that are currently in the NCEAS repo, even though
Windows R 3.3 builds are available. The R 3.2.4 win.builder build had no problem finding the R 3.2 builds. Here is an excerpt from the win.builder R-devel log:

```
Strong dependencies not in mainstream repositories:
  datapackage
Suggests or Enhances not in mainstream repositories:
  PKIplus
Availability using Additional_repositories specification:
  datapackage   yes   http://NCEAS.github.io/drat/
  PKIplus       yes   http://NCEAS.github.io/drat/
* checking package namespace information ... OK
* checking package dependencies ... ERROR
Package required but not available: 'datapackage'

Package suggested but not available for checking: 'PKIplus'
```

BTW - On local Windows 7, datapackage and PKIplus can be installed successfully with install.packages(), and the build/tests succeed.

**Comment by mbjones** [comment]
I think this is just saying that the `datapackage` is not available on CRAN.  It will pass once it is up there.

**Comment by gothub** [comment]
The R package `datapack` is now available on CRAN and package `PKIplus` has been replaced
with `openssl` which is now on CRAN.
