### ISSUE TITLE
improve clarity & possible typo in upload vignette?

### ISSUE THREAD

**Issue by cboettig** [DataONEorg/rdataone#135]
The vignette says: 

> Access rules are added to a DataObject using the addAccessRule method. The following access rule will grant user 'collins' changePermission access to the dataset after it is uploaded and available on a DataONE MN:

```r
accessRules <- data.frame(subject="uid=jsmith,o=NCEAS,dc=ecoinformatics,dc=org", permission="changePermission")
sciDataObj <- addAccessRule(dataObj, accessRules)
```

It looks like the reader is left to puzzle out what part of this command refers to the user `collins` (looks to me like a typo, the user is `jsmith`)?  It might also be good to provide a bit more guidance on how the `subject` string is constructed, and what all those arguments mean.  e.g. If I were to ask a collaborator to upload a file and grant me access, I'm really not sure what I'd tell them as far as how to construct the appropriate subject string for me.  

I'm sure this is documented elsewhere but I think should be clarified here.  Ideally I think it would be better to provide a function that could take the user as an argument directly, or a list of users and organization strings, if that is necessary.  The text just refers to "user 'collins'", rather than "user 'colins' in organization NCEAS etc; so it's not clear whether user names are unique only to an organization (or whatever the repeated dc arguments mean) or are globally unique.

**Comment by sbpcs59** [comment]
@cboettig Yep, the 'collins' is a typo. We don't completely discuss DataONE user identities in the vignettes - how a user obtains one, how to determine what the users' DataONE identity is, how it's used. Would having a section in the overview vignette that explains DataONE user identities in detail, and then
an example of a user obtaining their own identity here in the upload vignette be sufficient?

**Comment by cboettig** [comment]
@sbpcs59 it would be great to have documentation of that in the package, particularly if there's any package functionality that does or can facilitate that.  e.g. can I query "Scott Collins", (or better, query an email or ORCID ID, though I guess not everyone has an ORCID) and get a list of potential dataONE ids?  

At least knowing how to look up my own ID would be great, I actually have no idea how to do that  - no such information is listed under my profile on search.dataone.org either....  But long term I think the package should really have an easy way to give access permissions to, say, my co-authors or lab members using a syntax simpler than the perplexing `subject="uid=jsmith,o=NCEAS,dc=ecoinformatics,dc=org"` (which might be at fault for this typo in the first place, since it's harder to spot check that the user name is correct!)

**Comment by mbjones** [comment]
@cboettig Your username is actually under your user profile on search.dataone.org once you've logged in.  Look for the green box under the 'Settings | Apps' tab, which should have a field named 'Your user idnetity:'.  That said, I agree it can be hard to figure out.  We've made it so that, at least for ORCIDs, the username is the ORCID uri (e.g., for me, it is http://orcid.org/0000-0003-0077-4738). Each of the other ways of logging in produces a Distinguished Name (DN), which is also visible from the Settings screen (e.g., if I log in via Google, my Username is "CN=Matt Jones A729,O=Google,C=US,DC=cilogon,DC=org").  Other than under the Apps tab, we display the CN portion of the DN as a proxy for the identity, because the DN tends to be long and confusing.  Pointers on how to improve this all would be welcome.

What we don't have is a way to look up usernames for people, as they can log in via any of hundreds of different systems. And if they've never logged into DataONE before with their identity, we don't even know they exist.

**Comment by amoeba** [comment]
What if we use the accounts API on the CN to let a user in an interactive session find a valid value for the `subject` field?

```{r}
> search_for_bryce <- find_user(cn, name="bryce")
> search_for_bryce  # Char vec of length 2
[1] "CN=Bryce Mecum,O=Google,C=US,DC=cilogon,DC=org" "CN=Jim Bryce,O=Google,C=US,DC=cilogon,DC=org"
> bryce <- search_for_bryce[1]
> accessRules <- data.frame(subject=bryce, permission="changePermission")
> sciDataObj <- addAccessRule(dataObj, accessRules)
```

above, `find_user()` hits a URL like `https://search.dataone.org/cn/v2/accounts/?query=bryce`

**Comment by cboettig** [comment]
@mbjones thanks, yes, I saw that my profile lists my username as my ORCID uri, and I didn't try logging in any other way, so I was thinking I needed to look somewhere else to find values for O, C, DC, etc.  So how do I construct the appropriate subject string for this case? is it just: `subject="uid=https://orcid.org/0000-0002-1642-628X"` without the rest?  or is it `subject="uid=https://orcid.org/0000-0002-1642-628X", O=ORCID`?  

Right, I see your point that given all the different systems and users there's no easy solution here.  In the DataONE interface I did see a mechanism for creating groups, and the "add member" text seems to imply that I can _search_ for an existing user; however, if I type a name in it just appears to add that 'user' with no connection to a potentially already existing account?  

(At the moment I can't test, as I seem to have hit a bug where I get logged back out every time I try to log into search.dataone.org; switching browsers/clearing cache doesn't help...)

**Comment by cboettig** [comment]
@amoeba nice, that looks pretty compelling to me for a start!

**Comment by mbjones** [comment]
@cboettig The proper subject for an orcid and a google identity would be:
- `subject="http://orcid.org/0000-0003-0077-4738"`
- `subject="CN=Matt Jones A729,O=Google,C=US,DC=cilogon,DC=org"`

They have totally unrelated syntaxes, and in fact are just strings.  Use exactly what is quoted in the green box in the UI.

The search box for adding users only searches for accounts for people that have previously logged into DataONE.  It would be nice to extend this to ORCIDs via their public API, but we haven't done that yet.  There is no way to search for and list Google accounts and University accounts, so many of these will remain unknown to us until the user succeeds in logging in to DataONE.

**Comment by cboettig** [comment]
@mbjones thanks, that makes perfect sense.  I logged in using my Berkeley credentials, and the user box shows: "Carl Boettiger A45736".  Just to double-check, I would thus use that exact string (no `O=` stuff) as my `subject`?  

Not sure why I can no longer log in with my orcid credentials; it appears to work but then immediately returns me to a screen with the "sign in or sign up" after flashing my username briefly.

I do see that search works, e.g. if I search for Matthew Jones I get your different accounts, so very nice there.  

I also tried to link my accounts by logging in with Berkeley credentials and then pasting my ORCID uri into the search bar, but I get the error: `Could not request map identity: [LDAP: error code 32 - No Such Object]`

**Comment by cboettig** [comment]
@mbjones nevermind, I was looking at the box I see "My Account-> username".  I see under "Apps" tab that a full string is provided: `Your user identity: CN=Carl Boettiger A45736,O=University of California\, Berkeley,C=US,DC=cilogon,DC=org`

still puzzled why my orcid login stopped working...

**Comment by mbjones** [comment]
Does the green user box in the `Apps` tab show that value?  It should show the full DN, so I'm a little surprised.  When I login to UCSB and look, it shows the whole DN:

![Imgur](http://i.imgur.com/PWIqADk.png)

Seems like there's a bug with your Orcid -- I'll ask @lauren-walker and @leinfelder  to look into that.

**Comment by cboettig** [comment]
The full ID is correct in the apps tab, I was just expecting to see it in
the My Account tab, sorry. My mistake there.

Funny how the ORCID was working fine earlier today

On Wed, Mar 16, 2016, 5:15 PM Matt Jones <notifications@github.com> wrote:

> Does the green user box in the Apps tab show that value? It should show
> the full DN, so I'm a little surprised. When I login to UCSB and look, it
> shows the whole DN:
>
> [image: Imgur]
> <https://camo.githubusercontent.com/7386ced280bde61b7fe70d5918127b213533ff22/687474703a2f2f692e696d6775722e636f6d2f5057497141446b2e706e67>
>
> Seems like there's a bug with your Orcid -- I'll ask @lauren-walker
> <https://github.com/lauren-walker> and @leinfelder
> <https://github.com/leinfelder> to look into that.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/DataONEorg/rdataone/issues/135#issuecomment-197619487>
>
-- 

http://carlboettiger.info

**Comment by gothub** [comment]
@cboettig Carl - does your ORCID based authentication token still not work?

**Comment by cboettig** [comment]
@gothub thanks for the ping, I'll have to test that again.

**Comment by cboettig** [comment]
@gothub seems I still get an error when using the token from my ORCID. (though it's been a bit since I looked at this, maybe I'm doing something wrong).  

I logged into: https://search-stage.test.dataone.org using my ORCID ID and copied the token into my R session using `options`.  I then ran these steps: https://github.com/ropensci/EML/blob/master/inst/examples/metadata-repositories.Rmd

On the call to uploadDataPackage:

```r
packageId <- uploadDataPackage(d1c, dp)
```

I get: 

```
Your login certificate is missing or unreadable. You must login again via CILogon using 'dataone::downloadCert(CertificateManager())'
Error in auth_put_post_delete("post", url, encode, body, node) : 
```


Not quite sure if https://search-stage.test.dataone.org is the same as the "STAGING" server referred to in the .Rmd file.  (haven't tried repeating the testing with my institutional credentials instead, though they were working last time I checked)

**Comment by gothub** [comment]
@cboettig search-stage should be fine for generating your token. Are you defining it in your R session with something like:

```
options(dataone_test_token = "eyJhbGciOiJSUzI1...")
```

**Comment by cboettig** [comment]
@gothub Thanks! I had called the option "authentication_token" (since that's what https://search-stage.test.dataone.org/ called it).  Switching to "dataone_test_token" and all appears to upload without error now.

**Comment by mbjones** [comment]
@cboettig great.  So, I think this issue is now resolved.  There are undoubtedly documentation improvements still to be made, but I think we can close this ticket now that ORCID authentication is working for you.
