### ISSUE TITLE
More explicit CNode, getMNnode documentation?

### ISSUE THREAD

**Issue by cboettig** [DataONEorg/rdataone#136]
Probably sufficient just to add a link to wherever this is already documented.  It's nice that the docs tell me the possible arguments for `CNode`:

('PROD','STAGING', 'STAGING2,'SANDBOX', 'SANDBOX2','DEV', 'DEV2')

but it's not really clear what the different use cases are for each (PROD is perhaps self-evident to a developer-type, if not to all scientists), but I'm not clear on the difference between the rest. e.g. if I'm just testing out to see if things work, should I be using STAGING as in the vignette, or SANDBOX?  

Things are even less clear for getMNode, since there's no indication in the docs (or the vignettes) as to what are valid values for node identifiers.  (Again I'm sure this is clearly documented somewhere, I do have a vague memory that the DataONE API would also return a list of node ids along with other metadata about the nodes.  It would just be good to make this information transparently accessible to the R user ).  

What happens when I create a DOI in a throw-away test code using the Staging environment? is it reserved forever still or just removed/released?

**Comment by cboettig** [comment]
hmm, I'm actually more confused about how `CNode` and `getMNode` work.  The upload-data vignette shows you assigning the output of these functions to variables `cn` and `mn`:

```r
cn <- CNode("STAGING")
mn <- getMNode(cn, "urn:node:mnStageUCSB2")
```
I see `cn` is used by `getMNode`, but I don't see `mn` used anywhere else in the opening example (I do see that it can be used to request a DOI from the member node when creating a `dataObject`, though it's kinda unclear how this id compares with the `packageId` that the EML document in the example already declares).  Instead, I see the actual upload step, which I had thought would use `mn`, make it's own independent declaration of the environment and member node:

```r
d1c <- D1Client(env="STAGING", mNodeid="urn:node:mnStageUCSB2")
```
Why does `D1Client()` call here not make use of the existing `mn` object instead, or vice versa?

**Comment by mbjones** [comment]
@cboettig In reality, most users only need to know about PROD and STAGING2. PROD is the default production environment -- if no environment is specified in a call to CNode(), they get back PROD, assuming that they want to upload real data.  STAGING2 is our most stable testing environment, and can be used for inserting content when testing without polluting the production environment with garbage. We use it for all of our testthat tests.  The rest are all various flavors of testing environments, many of which are quite unstable and often down, and certainly running software that is not in production.

Once you have a CNode instance, you can call any of its services, such as getting a list of MNodes in that environment by calling `listNodes(cn)`.  A CNode 'knows' about all of its registered member node repositories.  By calling `getMNode(cn, "urn:node:mnStageUCSB2")`, you are asking the CNode to use the metadata about the repository to set up a new MNode instance, that can be used to execute any of the member repository services (such as getObject(), createObject(), etc.).  These CNode/MNode  classes represent the low-level DataONE API function for function.

In comparison, D1Client as a class provides a higher=level abstraction that requires less knowledge of how the DataONE network works, and tries to provide some integrated functions that handle the communications needed with any MN.  D1Client could use some further thought and development to streamline workflows for users.

Most (all?) test environments will probably not allow you to create a DOI with generateIdentifier(), unless they are configured to use the EZID test DOI shoulder. You'll probably get an error back if you try it with most nodes, though, except on production nodes that support it like the KNB.  All nodes must support UUID generation, so we generally test with that, and switch to getting a DOI only once we ready to move to production.

**Comment by cboettig** [comment]
@mbjones Super, this makes total sense.  I think the `upload-data` vignette would be simpler then if it omitted the `getMNNode` and `CNode` calls in the first example.  From the R perspective it's confusing, since they play no obvious role in the code execution (leaving me to worry that the code is doing something dreadful with inspecting the global environment for these variables), and being lower-level, are a bit less intuitive.  Then they can be discussed more explicitly in the part of the vignette that talks about DOIs (which might have a bit more documentation about how supported this feature is and when it should/shouldn't be used?).  Just a thought.

**Comment by mbjones** [comment]
Thanks for the feedback, @cboettig  -- @sbpcs59 can you try to incorporate edits along these lines?

**Comment by sbpcs59** [comment]
An explanation of the DataONE environments has been added to the "dataone-overview" vignette
in commit 234e83adaec12b5e2164f57655856adb809da2d3
