### ISSUE TITLE
confusion about `addData` syntax in upload-data vignette

### ISSUE THREAD

**Issue by cboettig** [DataONEorg/rdataone#137]
The upload-data vignette shows the following syntax for adding a science object and metadata object to a data package:

```
addData(dp, metadataObj)
addData(dp, dataObj, metadataObj)
```

I find this syntax confusing.  From the `addData` documentation, it looks like the first line is superfluous, and that the second line will both add the metadataObj and associate it with the dataObj if it has not already been added.  

The syntax shown here suggests that perhaps a user would want to associate multiple dataObj with the metadataObj?  That's reasonable, but surely the preferred syntax for that would be something like:
`addData(dp, dataObj1, dataObj2, metadataObj)`?  Does this also work?  

If so, to make the vignette code more intuitive to the reader, I would consider just showing the second command without the first.

**Comment by sbpcs59** [comment]
@cboettig yes, addData was overloaded a bit so to add a dataobject and associate the dataobject with
a metadataobject in one call. We were constrained a bit in the design to support the old R client v1.0
implementation, which was and still supported:

````
addData(dp, metadataObj)
addData(dp, dataObj)
insertRelationship(dp, subjectID=dataObj, objectIDs=metadataOb)
```
Because the "documents" package relationship is the most fundamental, if the "predicate" argument is
omitted, then the "http://purl.org/spar/cito/documents" and ""http://purl.org/spar/cito/isDocumentedBy"
relationships are created between the `dataObj` and `metadataObj`. Adding the third argument
to addData condensed this to:

```
addData(dp, dataObj, metadataObj)
```

Both dataObj and metadataObj have to be package members to have a relationship created between them, so in this case `metadataObj` is added if it is not already in the package.

I'm not sure if `addData(dp, dataObj1, dataObj2, metadataObj)` provides any more clarity, but if
we go this route, i would suggest:

```
addData(dp, c("dataObj1", "dataObj2"), metadataobj)
```
as the dataObj* and metadataObj have different roles in this method call

**Comment by cboettig** [comment]
Okay, thanks.  From the documentation it's a bit unclear what valid options for the `...` in `addData()` would be.  A syntax like `addData(dp, dataObj1, dataObj2, metadata = metadataobj)` would parallel the way `...` works in standard R objects like `data.frames` and `lists`.  

Maybe you meant 

```r
addData(dp, list(dataObj1, dataObj2), metadataobj)
```

instead of 

````
addData(dp, c("dataObj1", "dataObj2"), metadataobj)
```

? It seems very weird to me to pass strings (`"dataObj1"` in quotes rather than `dataObj1` without quotes) as the argument.

**Comment by sbpcs59** [comment]
@cboettig my mistake, `dataObj1`, `dataObj2` are `DataObjects`, not characters, so no quotes needed.
The correct example would be as you stated:

```
addData(dp, do=list(dataObj1, dataObj2), mo=metadataobj)
```

The role of argument 2 and 3 are very different, as arg 2 (a list with 1 or more members) gets
added to the datapackage, whereas arg 3 ("metadataobj") is added if not already in the datapackage, and then gets associated with the dataObjs by adding the CITO relationships 'documents' and 'isDocumentedBy'.

This 'shortcut' was intended to make things easier for the user, but having this method overloaded with
two tasks that it performs maybe causes more confusion than it's worth. Should we go back to having 
the original implementation be the only way to  associate 'science' data objects with a 
'metadata' object:

```
addData(dp, metadataObj)
addData(dp, dataObj)
insertRelationship(dp, subjectID=dataObj, objectIDs=metadataOb)
```

**Comment by cboettig** [comment]
I like the more concise syntax, but would still suggest that you have the metadata object be given by a _named_ argument to addData, while extracting the 0 or more `dataObj` to be added from `...` so the method works the way the familiar R base methods `data.frame()` and `list()` work.  If that's not practical, then the current syntax (using an explicit list of data objects) is already quite good; I would just show it in the documentation & vignette instead of the old syntax.  I think the two separate calls to `addData` are confusing.  

Note also that the lack of a return object is a bit confusing; since very few R methods pass by reference.  Also, this confused me regarding `addAccessRule()`, which appears to return a modified object rather than modifying the argument passed by reference?  (Or maybe it modifies both?) Anyway, the vignette and documentation should be standardized as to whether these functions are called using a pass-by-reference syntax or not; (and ideally should probably avoid that for simplicity for most R users).  Just a thought.

**Comment by sbpcs59** [comment]
@cboettig I've updated the documentation for `addData()` as you specified.

Regarding `addAccessRule()`, it returns an updated object and does not modify the argument by 
reference.

Note that the implementation for both `insertRelationship()` and `addData()` was to use the hash
package, so both of these originally updated by reference. Just today these were both updated
to also return the updated object, so users can call these methods in the traditional R way. The
roxygen docs for these have been updated to indicate that these methods update the original object.
I'd like to avoid at this late date reimplementing these `datapack` methods to not modify by ref, '
but if you or @mbjones believe this is advised, then I'll proceed.

**Comment by cboettig** [comment]
these changes sound good to me.  keeping the pass-by-reference for consistency on those methods sounds fine as long as they also return the updated object.  I'd suggest the main documentation (e.g. vignettes) stick with showing only the return-value style for simplicity (while of course documenting the pass-by-reference behavior in the function docs)

**Comment by sbpcs59** [comment]
Changes to addData() (and docs) made in commit 28368f2dcd0b63f4fc82af96f0046911e8b9f0d5. 
Changes to insertRelationship() made in commit 551b86d1ff08c15225b0b2a3e8e315e856c4adf3
