### ISSUE TITLE
uploadDataPackage example in the vignette fails

### ISSUE THREAD

**Issue by cboettig** [DataONEorg/rdataone#138]
Trying to run first code block in the vignette, after providing my authentication token as directed, I get several errors.

The first is easy to fix: it looks like D1Client has arguments named `x` & `y` while the vignette is showing arguments called `env` and `mNodeid`.  If I fix this, I can get `D1Client` to run successfully, but still get an error on `uploadDataPackage` call:

```
Error in .local(x, ...) : 
  Error creating urn:uuid:08cdb94c-33eb-4150-a034-e84571ac606c: Session is required to WRITE to the Node

```

**Comment by sbpcs59** [comment]
@cboettig the D1Client arguments have been fixed in the vignette, thanks. The second problem is
related to the authentication token. The R package can only check if the token is expired, and has to
leave it up to the DataONE server to decrypt and validate the token. The error message indicates that
authentication failed on the server. This message isn't very helpful from a user's point of view, and I'll log an issue in the DataONE bug tracking system to request that the error description includes an explanation of why the call failed, i.e. "authenticated user not found" or similar.

BTW - you can inspect the user identity and expiration date of your current token with:

```
am <- AuthenticationManager()
getTokenInfo(am)
````

Was it your ORCID that was being used for this request or your UC Berkeley id?
I'll assist today in tracking down why this id isn't authenticating.

**Comment by cboettig** [comment]
@sbpcs59 thanks, good to know it's just an auth issue.  Problem occurs with my Berkeley id.  Here's what I get:

```
am <- AuthenticationManager()
> getTokenInfo(am)
                                                                                 subject                 end expired
1 CN=Carl Boettiger A45736,O=University of California\\, Berkeley,C=US,DC=cilogon,DC=org 2016-03-18 12:08:50   FALSE
```

Using the token I just copied in options right now from the <search.dataone.org> interface having logged in with UCB credentials

**Comment by amoeba** [comment]
I see that the vignette uploads the data package to

`d1c <- D1Client("STAGING", "urn:node:mnStageUCSB2")`

@sbpcs59 is the auth problem due to using a token from the production environment when uploading to the development environment? If I run the vignette with a token from the production environment, I get the same error as @cboettig. If I switch my token to one from the development environment, the upload works.

**Comment by cboettig** [comment]
@amoeba good point, like you say I am trying to upload to the STAGING environment shown in the vignette.

hmm... is there a staging environment version of http://search.dataone.org that I can log into to get a 'staging' credential?  or is there another way to do that?

**Comment by amoeba** [comment]
There may be a better place, but I get my development tokens from https://search-stage.test.dataone.org/#account. Give that a shot. The UI is slightly different but you should be able to get a token. I imagine it'll be a different string than the token from production.

**Comment by mbjones** [comment]
That's exactly right.  Production tokens must come from https://search.dataone.org. All other environments share the test tokens, and can be gotten from any of the development environment search portals, including  https://search-stage.test.dataone.org/#account . This is clearly way to confusing for anyone not intimately familiar with the system to handle, and we need to be much more clear in our vignette's how to handle the PROD/STAGE2 distinction.

**Comment by cboettig** [comment]
@mbjones thanks for clarifying. Yup, explaining the different environments would be great, particularly since I think it is reasonable for end users to make use of the staging environment to test their code before they start uploading data into production.  

This suggests to me that the authentication token given to R in `options ` really should be namespaced.  I'm general I think it is good practice for packages to use namespaced options when they store tokens or other config.  In this case you might also have differing names so the methods can automatically get either the test or production token, and a user need not edit the token as well as the env argument to switch back and forth

**Comment by cboettig** [comment]
P.S.  does this mean there is also a testing URL for KNB where I could upload example EML and then query it in a web interface?  Likewise, I assume if I upload to a test env, I can also search that env with this 's search functions?  Are these test env data scrubbed clean on some regular interval?  Lots of questions, sorry.

**Comment by sbpcs59** [comment]
@cboettig you could use the staging environment and the member node urn:node:mnStageUCSB2 that is used in many of the examples in the vignettes:

```
cn <- CNode("STAGING")
mn <- getMNode(cn, "urn:node:mnStageUCSB2")
```

You can view content on this node directly at:

```
https://mn-stage-ucsb-2.test.dataone.org
```

https://search-stage.test.dataone.org allows searches for content on all nodes in the staging environment, and uses the DataONE UI skin.

The staging environment is fairly stable and usually has the released version of software
installed. Data may be wiped from this environment if space becomes critical or for other
reasons, but  in practical terms this doesn't happen very often.

**Comment by cboettig** [comment]
@sbpcs59 Thanks, that sounds promising.  So when I use a testing credential as suggested above, the vignette code runs just fine for me, returning `packageId` of `"urn:uuid:d4e7cd1b-9d67-464b-a3c5-80854c55fc5c"`.  However, when I try to search for this packageId from R I don't seem to find it:

```r
cn <- CNode("STAGING")
query(cn, searchTerms = list(id = packageId)
```

returns:

```
Error accessing https://cn-stage.test.dataone.org/cn/v2/query/solr/?q=id:*&fq=id:urn:uuid:d4e7cd1b-9d67-464b-a3c5-80854c55fc5c: NA
```

likewise trying to search for this id on https://search-stage.test.dataone.org/ returns no matches.  Any guess what I've done wrong?

**Comment by sbpcs59** [comment]
@cboettig for some reason that identifier is not publicly readable. Do you have an identifier
for one of the package members that I could check?

**Comment by cboettig** [comment]
@sbpcs59 ah, indeed my mistake!  yup, I was actually trying to test with a private id for starters so I could get a handle on how permissions work.  So, given that it's a private object it makes sense that it doesn't show up in a public search of course, but is there a way I can search/view it after authenticating (either online or from within the package?)

**Comment by sbpcs59** [comment]
@cboettig yes, you can search at search-stage.test.dataone.org and login to the user identity
that has access to the package. Note that this searches the coordinating node, so there will be
a delay from the time that the data was uploaded to when it shows up on the CN, usually 3-10 minutes.

**Comment by cboettig** [comment]
Nice!  Can this authenticated search also be done from R?

On Thu, Mar 17, 2016, 3:24 PM Peter Slaughter <notifications@github.com>
wrote:

> @cboettig <https://github.com/cboettig> yes, you can search at
> search-stage.test.dataone.org and login to the user identity
> that has access to the package. Note that this searches the coordinating
> node, so there will be
> a delay from the time that the data was uploaded to when it shows up on
> the CN, usually 3-10 minutes.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/DataONEorg/rdataone/issues/138#issuecomment-198108214>
>
-- 

http://carlboettiger.info

**Comment by cboettig** [comment]
Hmm, when I'm logged in (under the same Berkeley ID that I used to get the test credentials on the first place) to search-stage.test.dataone.org I still can't see that package; either in "my packages" or by searching for the uuid.  Very strange. Any ideas?

**Comment by sbpcs59** [comment]
@cboettig I'll check on this later today as I'm going offline for awhile, but was this the same
identifier as before?

**Comment by cboettig** [comment]
Yup, same identifier. Lemme know if I should run another test and post that ID too.  

Thanks!

**Comment by cboettig** [comment]
@sbpcs59 @mbjones thanks for the help.  Also tried just uploading a (non-public) package to STAGING and sharing it with @noamross but neither of us can see it.  ID returned for the package is `urn:uuid:4c61f7c6-6c47-4f5c-aa78-884bc29b5825`.  We were able to confirm if we upload public packages that they show up fine.  

Here's the script I ran to assign access rights and upload: https://github.com/ropensci/EML/blob/c6c2383327f387823abd8b6d018ad11c5c5d8546/inst/examples/metadata-repositories.Rmd,  runs without error messages up through the `uploadDataPackage()` command.

**Comment by mbjones** [comment]
@cboettig ok, I'll ask @sbpcs59 to take a closer look at what might be going on here.

**Comment by sbpcs59** [comment]
@cboettig The script looks fine to me, however, I found a problem with `uploadDataPackage()` on Friday, where the resource map permissions weren't getting set correctly (i.e. only public permissions getting set, not additional perms). This has been fixed in commit c15e64176d902bc36a4da450079824cb60821313

**Comment by cboettig** [comment]
@sbpcs59 Thanks, I've tried reinstalling both `dataone` and `datapack` from GitHub and re-running the same script.  Up until the `addData()` call things appear to run fine, then I get the error:


```
addData(dp, dataObj, metadataObj)
An object of class "DataPackage"
Slot "relations":
<hash> containing 1 key-value pair(s).
  relations : c("urn:uuid:7ba7cd2f-df14-40c0-915b-0ed16b8eb77f", "urn:uuid:1eec0820-2259-41b1-b98c-2daed917cb98") c("http://purl.org/spar/cito/documents", "http://purl.org/spar/cito/isDocumentedBy") c("urn:uuid:1eec0820-2259-41b1-b98c-2daed917cb98", "urn:uuid:7ba7cd2f-df14-40c0-915b-0ed16b8eb77f") c("NA", "NA") c("NA", "NA") c("NA", "NA")

Slot "objects":
Error in as.character.default(x[[k]]) : 
  no method for coercing this S4 class to a vector
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux stretch/sid

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] datapack_1.0.0 dataone_2.0.0 

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3      roxygen2_5.0.1   XML_3.98-1.4     digest_0.6.9     withr_1.0.1      plyr_1.8.3       R6_2.1.2         jsonlite_0.9.19  magrittr_1.5    
[10] git2r_0.14.0     httr_1.1.0       stringi_1.0-1    uuid_0.1-2       curl_0.9.6       parsedate_1.1.1  hash_2.2.6       devtools_1.10.0  tools_3.2.3     
[19] stringr_1.0.0    base64enc_0.1-3  memoise_1.0.0    knitr_1.12.3     redland_1.0.17-7
```

**Comment by sbpcs59** [comment]
@cboettig I just reran the script and found that the following line needs to be updated:

`library("datapackage")` change to `library("datapack")`

and

`addData(dp, dataObj, metadataObj)` change to `dp <- addData(dp, dataObj, metadataObj)`

Also, regarding the query - it appears that right now content is not syncing from the member node
to the cn, so this query from your script isn't going to work until this is resolved:

```
query(CNode("STAGING"), searchTerms = list(id = packageId))
```

You can query the member node however:

```
cn <- CNode("STAGING")
mn <- getMNode(cn, "urn:node:mnStageUCSB2")
query(mn, searchTerms = list(id = packageId))

**Comment by sbpcs59** [comment]
It appears that all problems mentioned in this issue have been fixed / addressed.
