### ISSUE TITLE
getD1Object: Java heap space errors

### ISSUE THREAD

**Issue by couture322** [DataONEorg/rdataone#14]
I have been getting errors after bringing in many datasets using “getD1Object()” for each dataset. It looks like the memory fills up after a while and I get the following error: 
“Error in .jnew("java/lang/String", databytes, "UTF-8") :
  java.lang.OutOfMemoryError: Java heap space”
Ben L helped me figure out a work around by increasing my heap space
 “options( java.parameters = "-Xmx4g" )”
 and this has been working for me in the short term, but it sounded like this is something that could/should be fixed.

**Comment by mbjones** [comment]
No longer using Java, so this issue should no longer be an issue in the new release.
