### ISSUE TITLE
Replace PKI-plus suggestion with openssl package

### ISSUE THREAD

**Issue by cboettig** [DataONEorg/rdataone#143]
@jeroenooms points out the the `openssl` (which is on CRAN), should do everything you're doing with PKIplus here.  Might also let you move it out of suggests and into imports.

**Comment by jeroenooms** [comment]
The `openssl` package also replaces `base64enc` :)

**Comment by sbpcs59** [comment]
@cboettig @jeroenooms Nice! Thanks for the suggestion.

`openssl` does the job:

```
> library(openssl)
> cert <- read_cert("/tmp/x509up_u501")
> as.list(cert)$subject
[1] "DC = org, DC = cilogon, C = US, O = Google, CN = Peter Slaughter A10499"
> as.list(cert)$validity
[1] "Mar 22 16:18:11 2016 GMT" "Mar 23 10:23:11 2016 GMT"
```

**Comment by sbpcs59** [comment]
The recent changes to openssl for [cert/subject](https://github.com/jeroenooms/openssl/issues/24) provide the functionality needed by dataone and has been tested on Mac, Win & Linux. This fix is critical to dataone as the cert subject is used for the sysmeta rightsholder if not provided by the user, so we shouldn't release the package until this is available on CRAN.

@jeroenooms when is the next release of openssl (on CRAN) planned for?

**Comment by jeroenooms** [comment]
This is on CRAN now. Make sure to add 'openssl >= 0.9.3' to your description.

**Comment by sbpcs59** [comment]
@jeroenooms excellent, thx!

**Comment by sbpcs59** [comment]
This change was made in commit d2042424f35b017d5432078f676db355c6ae71a0
