### ISSUE TITLE
describeObject can't read a PID when getSystemMetadata can

### ISSUE THREAD

**Issue by amoeba** [DataONEorg/rdataone#151]
I just ran describeObject on a PID that is on `dev.nceas` and got not authorized even though I can read the object's sysmeta. Is it possible that describeObject isn't reading my token correctly?

```{r}
> describeObject(mn, "urn:uuid:5ff45d6a-a030-43e9-aca6-aadba95ddbbe")
Exception name: org.dataone.service.exceptions.NotAuthorized 
Exception detail code: 1400 
Exception description: dataone-exception-description

> getSystemMetadata(mn, "urn:uuid:5ff45d6a-a030-43e9-aca6-aadba95ddbbe")
.. returns sysmeta
```

**Comment by gothub** [comment]
@amoeba yep, it looks like `describeObject()` doesn't go through the authentication mechanism at
all. The following needs to happen:

- add HEAD requests to the authentication mechanism
- have `describeObject()` make an authenticated request
- check other methods that don't user authentication and verify that they don't really need it
  - i.e. 'listQueryEngines()' doesn't need authentication
- add an authenticated test to the unit tests for 'describeObject()` (not run on CRAN)

**Comment by gothub** [comment]
Added an authenticated http HEAD request mechanism that describeObject now uses, in addition
to a unit test. These were added in commit 30433cb13faaf8488837ef63e2fde119c759e5fe
