### ISSUE TITLE
Package warns about a login cert being missing or unreadable

### ISSUE THREAD

**Issue by amoeba** [DataONEorg/rdataone#161]
If you run a `dataone` function like `query` without setting a token, you get warned:

> Your login certificate is missing or unreadable. You must login again via CILogon using 'dataone::downloadCert(CertificateManager())'
> Attempting to call as public user without being authenticated.

However, 

- This presents the user with a warning even though there is nothing wrong with running certain `dataone` functions without a certificate. I might expect either no feedback at all or just short message rather than a warning.
- We're encouraging the token use case over certs. This message only talks about certs.
- Rather than "Attempting to call as public user without being authenticated.", maybe a more user-friendly message could be used that avoids jargon. Blanking on a better sentence at the moment.

**Comment by gothub** [comment]
- Regarding the "login certificate missing" message. Options to improve this
  - [ ] print both a "token missing" message and "login certificate missing" message if neither is found
  - [ ] print a simplier message indicating that the user isn't authentication and refer them to the documentaion
  - [ ] don't print either "login cert missing" or "token missing"
  - [ ] something else?

- Regarding the  "Attempting..." message - this is indirectly telling the user that their query may not return all the expected results as they are searching as the public, unauthenticated user and not an authenticated user with a valid token or certificate.  Options to improve this
 - [ ] print a more verbose message
 - [ ] print a message referring them to the documentation for an explanation
 - [ ] don't change the message
 - [ ] something else?

**Comment by amoeba** [comment]
How crazy would it be if running an operation that is normal to run without a token, such as `query` or `getSystemMetadata`, there is no `message`/`warning`?

**Comment by gothub** [comment]
@amoeba The `query` method can be called with valid authentication, in which case it might
return different results than an unauthenticated call, so I think we are trying to remind the user of that. I'm fine with changing all D1 calls that call `auth_get` to not return any message/warning if no authentication is found. What do you think @mbjones ?

**Comment by amoeba** [comment]
>  so I think we are trying to remind the user of that.

I think that's good. It's probably better to send out a warning and avoid confused users at the cost of a warning/message popping up in the user's console (which I hate because it puts output I don't care about in front of me).

**Comment by mbjones** [comment]
It bothers me every time I get that warning, and I've thought we should
correct it forever.  So, I'm all for the suggestion that there be no
warning when normal operations are executed.

The one exception might be is if someone has an expired token or expired
cert in their request, in which case they would expect to be authenticated,
but in fact are not.  In that case, I would argue that a warning is
appropriate, and should target the right case.  For example, "You attempted
this operation with an expired token, so you were not authenticated.  You
may wish to try again with a valid token."

**Comment by gothub** [comment]
A message is now only printed when an expired token or cert is found, if that token or cert would have been used for authentication, i.e. dev vs prod environment. The following message is printed if an expired token is found:

```
You attempted this operation with an expired token, so you were not authenticated.
You may wish to try again with a valid token
Attempting to perform this operation as the public user without being authenticated.
```

A similar msg is printed for an expired cert.

Let me know if you would like to change the message that is printed.

This change was made in commit 4e1cda5bc1df9c5b0205bfdd720d87cd38278c9c

**Comment by amoeba** [comment]
That looks like a good improvement. What do you think about something like this:

>  Your {token|certificate} is expired. Only showing publicly readable results. See ?some_help_page for more information.

where ?some_help_page discusses authentication/tokens/certs in more detail. I like this because I appreciate when warnings/messages are a single linen and it links directly to a place to get more/enough information to understand the problem and its implications.
