### ISSUE TITLE
getSystemMetadata and other methods don't escape the PID

### ISSUE THREAD

**Issue by amoeba** [DataONEorg/rdataone#163]
I was trying to run:

``` r
mn_lter <- MNode("https://gmn.lternet.edu/mn/v1")
getSystemMetadata(mn_lter, "https://pasta.lternet.edu/package/metadata/eml/knb-lter-bnz/12/19")
```

but I get:

```
NULL
Warning message:
In .local(x, ...) : Error getting SystemMetadata: NA
```

I checked to see if this works by accessing the system metadata in my browser

https://gmn.lternet.edu/mn/v1/meta/https://pasta.lternet.edu/package/metadata/eml/knb-lter-bnz/12/19

which returns a 404. If I escape the PID portion of the URL, it works:

https://gmn.lternet.edu/mn/v1/meta/https%3A%2F%2Fpasta.lternet.edu%2Fpackage%2Fmetadata%2Feml%2Fknb-lter-bnz%2F12%2F19

If you look [here](https://github.com/DataONEorg/rdataone/blob/2bea86148897de17d5760b439dadad9213fda1ed/R/MNode.R#L254), you'll see this code:

``` r
    # TODO: need to properly URL-escape the PID
    url <- paste(x@endpoint, "meta", pid, sep="/")
```

which looks like the culprit. I think this should be changed, as the DataONE API spec says PIDs should always be escaped in the REST API. There may be many more instances of failing to escape PIDs so maybe a codebase audit is in order.

**Comment by amoeba** [comment]
The [relevant portion](http://jenkins-1.dataone.org/jenkins/job/API%20Documentation%20-%20trunk/ws/api-documentation/build/html/apis/rest_comms.html#url-path-parameters) of the arch docs says:

> Some parameters are passed as part of the REST service URL path (e.g. /get/{pid}). Such values MUST be encoded according to the rules of RFC3986 with the additional restriction that the space character MUST be encoded as “%20” rather than “+”. Examples of DataONE REST URLs for retrieving an object (i.e. the get() operation):

which references [rfc3986](https://tools.ietf.org/html/rfc3986). @mbjones mentioned he had delayed escaping pids in favor of finding an escaping mechanism in R that was perfectly compatible with that RFC. Maybe we can find one.

**Comment by amoeba** [comment]
For reference, the source code for R's bulit-in url encoding function is [here](https://github.com/wch/r-source/blob/af7f52f70101960861e5d995d3a4bec010bc89e6/src/library/utils/R/URLencode.R)

**Comment by vdave** [comment]
The default encoding process should be used in preference to no encoding. The only major difference will be on how spaces are treated - and there is no white space in DataONE identifiers.

**Comment by amoeba** [comment]
Good point on both fronts!

**Comment by mbjones** [comment]
This should apply to all methods that encode PIDs in URLs, not just getSystemMetadata.

**Comment by gothub** [comment]
All services that send pids via the url have been encoded using URLencode(pid, reserved=T).
Added in commit 2437ac5e4c9123a89340a3df51b3ebd38bda5d2c
