### ISSUE TITLE
Allow passing in curl debugging options to all appropriate fxns

### ISSUE THREAD

**Issue by sckott** [DataONEorg/rdataone#17]
No way to pass in curl debugging options right now. We can do something like

```r
library(dataone)
library(httr)
describe(node, pid, config=verbose())
```

```r
prints out verbose output for the curl call...
```

**Comment by mbjones** [comment]
We don't depend directly on curl, but instead use httr, which used to import RCurl. Recently httr switched to using 'curl' over 'RCurl', and so its possible that we may or may not depend on curl at all in future implementations, and so I am reluctant to have our method signatures include curl-specific parameters.  Closing this for now, but please let me know if you strongly think it should be provided.
