### ISSUE TITLE
Make getPackage() easier to use

### ISSUE THREAD

**Issue by gothub** [DataONEorg/rdataone#178]
Currently `getPackage()` requires that the package identifier (resource map id) is
specified for the package to be downloaded. This is also the requirement of the
DataONE service that this R method calls, and 'getPackage()' simply calls the DataONE service.
A reasonable error is returned and printed from DataONE if the id is not the package id:

```
Warning message:
In .local(x, ...) :
Error calling getPackage: The given pid doi:10.5063/F1DR2SDD is not a package id (resource map id). Please use a package id instead.
```
While this message is helpful, it doesn't necessarily get the user any closer to a solution.

Should this method be upgraded to check if the specified pid is a package member. If yes, it could determine the package that the pid belongs to and download that package. If the PID belongs to 
multiple packages, then don't download anything and tell the user which packages the PID belongs to.

Also, should there be a package size download limit imposed, similar to the one in place
for MetacatUI?

**Comment by amoeba** [comment]
I am a fan of automatically doing the intended thing. Given that metadata PIDs are first-class citizens in our web UI and package PIDs are second-class, I would expect users would want `getPackage` to work on package member PIDs and not just the package's resource map PID. 👍 

> Also, should there be a package size download limit imposed, similar to the one in place
for MetacatUI?

Good catch. I forgot about that. I think it's a good idea. But if we fix the issue in Metacat, I guess we'd want to re-release this package without the limit. Not a big deal.

**Comment by gothub** [comment]
`getPackage` now accepts a pid for the resource map, metadata object or data object
for a package, and will download the related package. Updated in commit bb2b922b442762d57439da03e09ca649b431893e
