### ISSUE TITLE
query function returns odd results for multi-valued fields

### ISSUE THREAD

**Issue by amoeba** [DataONEorg/rdataone#179]
Just ran into this. With a query like:

```{r}
results <- query(mn, list(q = '-readPermission:"public"',
                          fl = 'identifier,formatType,resourceMap',
                          sort = 'dateUploaded+asc',
                          rows = '2000'),
                 as='data.frame')
```

I expect my result to have three columns but instead it has 660, one for each unique value of `resourceMap`:

```{r}
> head(names(results))
[1] "identifier"                                                              
[2] "formatType"                                                              
[3] "resourceMap..resource_map_urn.uuid.81289985.583b.4d99.a2d5.a19b8a74c8c8."
[4] "resourceMap..resource_map_doi.10.18739.A2ZS7F."                          
[5] "X.resourceMap_autogen.2016032220435043593.11."                           
[6] "X.resourceMap_autogen.2016032221522540687.4."     
```

It kinda looks like query isn't handling multi-value Solr fields correctly. Haven't looked into why just yet.

**Comment by amoeba** [comment]
I suppose we'd have to make a choice about how multi-valued fields' values get forced into a single cell. Perhaps we separate them by a character that can never appear in a PID/SID? Is that a space?

From https://releases.dataone.org/online/api-documentation-v2.0/design/PIDs.html
> The characters that may appear in an identifier string acceptable to the DataONE system is constrained by the XMLSchema definition (Types.Identifier), which is essentially a string of length greater than zero but less than 800 characters with no whitespace (spaces, tabs, non-printing characters, carriage returns, new lines). 

and:

https://releases.dataone.org/online/api-documentation-v2.0/apis/Types.html#Types.NonEmptyNoWhitespaceString800

> A NonEmptyNoWhitespaceString800 is a NonEmptyString800 string that doesn’t allow whitespace characters (space, tab, newline, carriage return). Unicode whitespace characters outside of the ASCII character set need to be checked programmatically.

**Comment by amoeba** [comment]
Looking at the source for query, I see that it apparently intends to adapt to this with `plyr::rbind.fill` but I don't think it's working:


```{r}
> df1 <- as.data.frame(res[[i]], stringsAsFactors=FALSE)
> df1
                                     identifier formatType
1 urn:uuid:e3f0150a-c2fc-4d61-b346-398e105f72cf       DATA
  resourceMap..resource_map_urn.uuid.81289985.583b.4d99.a2d5.a19b8a74c8c8. resourceMap..resource_map_doi.10.18739.A2ZS7F.
1               resource_map_urn:uuid:81289985-583b-4d99-a2d5-a19b8a74c8c8               resource_map_doi:10.18739/A2ZS7F
> dfAll <- rbind.fill(dfAll, df1)
> dfAll
                                     identifier formatType
1 urn:uuid:e3f0150a-c2fc-4d61-b346-398e105f72cf       DATA
2 urn:uuid:e3f0150a-c2fc-4d61-b346-398e105f72cf       DATA
  resourceMap..resource_map_urn.uuid.81289985.583b.4d99.a2d5.a19b8a74c8c8. resourceMap..resource_map_doi.10.18739.A2ZS7F.
1               resource_map_urn:uuid:81289985-583b-4d99-a2d5-a19b8a74c8c8               resource_map_doi:10.18739/A2ZS7F
2               resource_map_urn:uuid:81289985-583b-4d99-a2d5-a19b8a74c8c8               resource_map_doi:10.18739/A2ZS7F
```

**Comment by gothub** [comment]
@amoeba I verified this fix, nicely done!
