### ISSUE TITLE
dataone::query returns a nested rdf+xml file

### ISSUE THREAD

**Issue by LiamBurke24** [DataONEorg/rdataone#196]
Hey all, 

I am trying to download some data using the D1Client, and am getting the output as an rmd+xml file. I have combed through the docs but haven't seen a solution that has worked yet... Here is what I have thus far: 

```
# query by doi
doi <- "doi:10.6073/pasta/6b03a068eb72af9b2ba14d633c9cb60c" 
cn <- dataone::CNode("PROD") 
queryParams <- list(q='id:"doi:10.6073/pasta/6b03a068eb72af9b2ba14d633c9cb60c"', rows="5")
result <- dataone::query(cn, solrQuery = queryParams, encode = TRUE, as = "data.frame", parse = TRUE)
dataUrl <- result[1, "dataUrl"]
```
The query returns a url for the package in a rdf+xml format. I need to convert this into an R list for later use. I figured that the getData function would have an argument for this, but I haven't found one. Below is my best attempt at a download.  
```
# download 
d1c <- dataone::D1Client("PROD", result[,"authoritativeMN"])
pid <- doi
obj <- dataone::getDataObject(d1c, identifier = pid)
data <- rawToChar(getData(obj))
```

Many thanks in advance for your help. I have been rally impressed thus far with your package and your prior assistance.

**Comment by gothub** [comment]
@LiamBurke24 the file that you searched for and downloaded is an rdf/xml file, which is correct. 
This file is the [resource map](http://www.openarchives.org/ore/1.0/datamodel#Resource_Map) that is like a data package manifest. I think what would be more useful to you is the 
metadata pid that goes along with this resource map, which is "https://pasta.lternet.edu/package/metadata/eml/knb-lter-hbr/33/6". 

The data for this package is currently only on the LTER member node, which does not support
the `getPackage` R call you could have used to download the package, given the resource map id.

What you can do instead, is go to https://search.dataone.org and copy/paste this metadata pid into
the "Identifier" field (click on "Identifier" under "Filter by"). Hit enter, then click on the dataset that is displayed to the right. On the next screen, you will see a "Download All" button, but don't click it,
as it shouldn't really be displaying and will not work for this member node. What you can do instead is to click the "download" button next to each dataset.

The searching that your first set of R commands did (nice!) is performed by the
`getDataObject` method internally, so for any other id you are looking for you can shorten the
script to:

```
pid <- "doi:10.6073/pasta/6b03a068eb72af9b2ba14d633c9cb60c" 
d1c <- dataone::D1Client("PROD", "urn:node:LTER")
obj <- dataone::getDataObject(d1c, id = pid)
data <- rawToChar(getData(obj))
```

Note that the member node in the `D1Client` call is ignored by `getDataObject`

Is there other data that you need to download? If you have other metadata pids, I can show you
how to identifier all the data objects in the package for the metadata pid. Note that the
next release of `dataone` R package will have a method that will do this for you.

**Comment by LiamBurke24** [comment]
@gothub Thank you for your many suggestions! I appreciate the improvements you made to my code! 

Some context that I left out in my last comment is that I am trying to build a function for PEcAn (https://github.com/PecanProject) that allows users to upload data with only a doi. Although it seems like this won't be possible for all datasets given that not all member nodes have upgraded to V2 yet (which explains why I couldn't use `getPackage` when I tried it...).  

Is it possible to sort which MN's can use the `getPackage` feature? I can envision an interface where users enter a desired doi and receive a prompt if they need to manually download the data because the MN is not up to date... 

Also, I'm looking forward to the new release! Is there a rough timeline for that? 

Thanks so much,
Liam

**Comment by LiamBurke24** [comment]
Also, here are a couple of other datasets that I'd like to download: 
https://doi.org/10.3334/ORNLDAAC/209
https://doi.org/10.3334/ORNLDAAC/819

These data sets from ORNL DAAC do not have doi but they do have the resource maps that you were referring to. So, I tried to use the resource maps to do the download via the `bagit` function. Looks like this: 

```
cn <- CNode("PROD")
mn <- getMNode(cn, "urn:node:ORNLDAAC")
packagePid <- "resourceMap_209.xml"
bagitFileName <- getPackage(mn, id=packagePid)
``` 
I get the following error: 

```
Your login certificate is missing or unreadable. You must login again via CILogon using 'dataone::downloadCert(CertificateManager())'
Attempting to call as public user without being authenticated.
Error calling getPackage: Client error: (404) Not Found
```
I figure that this has something to do with the MN authentication... I set the mnId as `"urn:node:ORNLDAAC"` as a guess because I can't use the`getMNId` function without the d1 client object which itself requires the nodeId. So I guess I'm stuck in a loop here. Thanks for your help with this!!

**Comment by gothub** [comment]
@LiamBurke24 The `Your login certificate` message is a bit overkill and has been removed forf
the next release of the `dataone` package. Some datasets in DataONE are not viewable by the
public, so for example, if you had datasets you created that were not publicly readable, and you did
not provide user authentication, you would not be able to read your own data. This message just
confuses the issue so has been removed.

The issue that you are encountering however, has to do with the `getPackage` service not being
available/implemented on the member node that you sending the `getPackage` request to, so you get the HTTP 404 "Not found" error. This is not related to the DataONE API version, but whether or not the member node has implemented this optional service.

The `dataone` R package should check if this service is available on the requested member node
and print an error if it is not. I'll enter a github issue for this, as this needs to be added.

In the meantime. you could check any warning message returned from the `getPackage` call, a
404 error will be returned if the `package` service is not found. Not a pretty solution, but 
we will try to fix this for the next release.

**Comment by LiamBurke24** [comment]
Thank you so much for clarifying. So, to clarify, there is no way of determining which member nodes work with `getPackage` before attempting to run a query? I guess it would be nice to have a list of all nodes that are up-to-date and those that cannot yet be accessed.

**Comment by LiamBurke24** [comment]
Is it also possible that I'm getting the 404 error from a bad mnId? Like I mentioned before, I can't figure out how to find the mnId without the mnId :)

**Comment by gothub** [comment]
Maybe the `resolve` method would help here:

```
cn <- CNode("PROD")
locations <- resolve(cn, pid="resourceMap_209.xml")
locations
```
prints out
```
$data
     nodeIdentifier                                  baseURL
1 urn:node:ORNLDAAC http://mercury-ops2.ornl.gov/ornldaac/mn
2       urn:node:CN                https://cn.dataone.org/cn
                                                                     url
1 http://mercury-ops2.ornl.gov/ornldaac/mn/v1/object/resourceMap_209.xml
2                https://cn.dataone.org/cn/v2/object/resourceMap_209.xml
```

Note that resource maps and metadata can be located on `urn:node:CN`, but data files are
not copied to that node, as it is the controlling node for the entire network.

**Comment by LiamBurke24** [comment]
Thanks! Its as you said earlier. The MN must not be set up with getPackage. 

Is there a master list of compatible MNs? or is this just something that needs trial and error to address?  

Many thanks.
-Liam

**Comment by gothub** [comment]
The `listNodes` method provides a list of service "bundles" that each node supports, but 
it's not reporting the `MNPackage` bundle, that has the `getPackage` service:
```
nodes <- listNodes(CNode("PROD"))
result <- lapply(nodes, function (node) {
  if(node@identifier == "urn:node:KNB") show(node@services)
})

              name version available
1           MNCore      v1      true
2           MNCore      v2      true
3           MNRead      v1      true
4           MNRead      v2      true
5  MNAuthorization      v1      true
6  MNAuthorization      v2      true
7        MNStorage      v1      true
8        MNStorage      v2      true
9    MNReplication      v1      true
10   MNReplication      v2      true
```

This should show `MNPackage` but it doesn't so  I've logged an issue for DataONE to look into this, but for right now your best bet is to handle the error in your code.

**Comment by LiamBurke24** [comment]
Alright! thanks so much for walking me through this. Hopefully this makes it into the new release!
