### ISSUE TITLE
Create CNode class

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/rdataone#2]
Create a CNode class to represent Coordinating nodes, and implement all CN client-side interfaces.

- [x] Implement CNode class and stub out methods
- [x] Implement CNode() constructor
- [x] Implement ping()
- [x] Implement listFormats()
- [x] Implement getFormat()
- [x] Implement listChecksumAlgorithms()
- [ ] Implement getLogRecords()
- [x] Implement listNodes()
- [x] Implement reserveIdentifier()
- [x] Implement generateIdentifier()
- [x] Implement hasReservation()
- [x] Implement setObsoletedBy()
- [ ] Implement delete()
- [x] Implement archive()
- [x] Implement get()
- [x] Implement getSystemMetadata()
- [x] Implement describe()
- [x] Implement resolve()
- [x] Implement getChecksum()
- [x] Implement listObjects()
- [ ] Implement search()
- [x] Implement query()
- [x] Implement getQueryEngineDescription()
- [x] Implement listQueryEngines()
- [x] Implement getMNode()

**Comment by sbpcs59** [comment]
- delete() requires admin privilege so will not be implemented. 
- search() has been superceded by query(), so will not be implemented

**Comment by sbpcs59** [comment]
getLogRecords() will be implemented in 2.1.0
