### ISSUE TITLE
Create a downloadObject function

### ISSUE THREAD

**Issue by maier-m** [DataONEorg/rdataone#217]
Create a downloadObject function to assist users with getting files from dataONE. An alternative now is to use:

`foo <- dataone::getObject()`
`writeBin(foo)`
But this will fail with files >2GB because of limitations inherent to `R`

A downloadObject function should be part of the D1Client module to preserve API congruence.

Additionally, the function should use `mediaType` and `fileName` sysmeta when possible to name files and give file extensions.

**Comment by gothub** [comment]
Completed by @maier-m in commit 82fe053181000ded8d7b9c27a3453e692f6b5fe2
