### ISSUE TITLE
Feature request: Make getDataPackage/getDataObject calls to resolve() retry on failure

### ISSUE THREAD

**Issue by amoeba** [DataONEorg/rdataone#228]
It's my understanding that these methods (and maybe others?) make use of the `CN.resolve()` API call to do their downloading. Sometimes replicas are actually bad and a call to `MNStorage.read()` will fail. It seems like these methods could retry other replicas when the first replica fails.

**Comment by gothub** [comment]
@amoeba this was the initial design, and with the changes implemented for issue #266, all replicas are tried until success.

**Comment by amoeba** [comment]
Awesome, thanks @gothub !
