### ISSUE TITLE
Create `pkgdown` site

### ISSUE THREAD

**Issue by jeanetteclark** [DataONEorg/rdataone#254]
It would be nice to have a `pkgdown` generated site hosted on GitHub pages so that users can more easily see and interpret the vignettes.

I've created the structure on my fork. The deployed site on my fork can be viewed here: https://jeanetteclark.github.io/rdataone/

PR to come

**Comment by mbjones** [comment]
@gothub is this merged and ready to be included in 2.2.0? If so, please add that milestone.

**Comment by gothub** [comment]
The pkgdown files will be included in the 2.2.0 release. Deploying the files to an appropriate site will be tracked in issue
https://github.com/DataONEorg/rdataone/issues/273.
