### ISSUE TITLE
Change 'lazyLoad' behavior

### ISSUE THREAD

**Issue by gothub** [DataONEorg/rdataone#258]
Update the 'lazyLoad' parameter for 'getDataPackage()' and 'getDataObject()' so that:
1. when 'lazyLoad=T', the object will always be lazy loaded, regardless of size
2. when 'lazyLoad=F' and 'limit' is not specified, objects will not be lazy loaded, regardless of size
3. when 'lazyLoad=F' and 'limit=<size>' is specified, objects will not be lazy loaded if they are smaller than the 'size' specified, if objects are larger than the 'size' specified, they will be lazy loaded.

**Comment by mbjones** [comment]
Thanks for the summary, @peter. 

- I agree with (1)
- For (2), given that `limit=1MB` is the default setting, I think that limit should be applied by default if `limit` isn't explicitly set. That is the point of having a default. So I would change (2) to:
    - when 'lazyLoad=F' and 'limit' is not specified, objects will not be lazy loaded, except that they will be lazy loaded when they exceed the default size limit of 1MB
- I agree with (3)

**Comment by gothub** [comment]
Update in commit d11a69bb2aa70c9964945cb258eebf8e8b9ec534

Documentation changed for command line roxygen and 'upload-package' vignette. Here is an excerpt from the command line docs for '?getDataPackage':

<img width="627" alt="Screen Shot 2020-09-02 at 2 01 05 PM" src="https://user-images.githubusercontent.com/6412946/92036298-d9637180-ed24-11ea-807b-2b5a07d7f933.png">
