### ISSUE TITLE
Next release version number considerations

### ISSUE THREAD

**Issue by gothub** [DataONEorg/rdataone#265]
@mbjones @amoeba currently the next release is slated to use version 2.2.0, updated from the current CRAN version of 2.1.4. This issue raised the question of whether the version needs to be updated to 3.0.0, as explained below:

According to semantic versioning (https://semver.org/):
- MAJOR version when you make incompatible API changes,
- MINOR version when you add functionality in a backwards compatible manner, and
- PATCH version when you make backwards compatible bug fixes.

This next release will use a new parameter that is now available in datapack::DataObject(), for example, in D1Client:
```
    do <- new("DataObject", id=sysmeta, dataobj=bytes, dataURL=dataURL, checksumAlgorithm=checksumAlgorithm)
```
where `checksumAlgorithm` is the new parameter in datapack 1.4.0.

The function `datapack::DataObject` sets a default for `checksumAlgorithm`, so current dataone scripts that don't specify this parameter will work.

It appears then, that this is not an 'incompatible API change' so the version of 2.2.0 is appropriate. 
Is this correct?

On a side note, I was planning on requiring datapack 1.4.0 in DESCRIPTION.

**Comment by mbjones** [comment]
Yes, I think your analysis is spot on. 2.2.0 seems fine given that functionality was extended but not in a way that breaks existing uses.

**Comment by amoeba** [comment]
Sounds great, thanks @gothub.

**Comment by gothub** [comment]
Version number updated to '2.2.0' in commit c098e809f0ccc13e852aafcbe70beca0eb8583a5
