### ISSUE TITLE
Release v2.2.2

### ISSUE THREAD

**Issue by gothub** [DataONEorg/rdataone#281]
- [x] close any issues assigned to this release
- [x] check and update contributors list and update DESCRIPTION/CITATION if needed
- [x] Update version number, publish date, etc. in DESCRIPTION
- [x] check that all new functions have unit tests
- [x] update NEWS
- [x] update cran_comments
- [x] run revdepcheck::revdep_check()
- [x] run tests with cran=true and network cable unplugged
    - devtools::check(vignettes = FALSE, env_vars = c(NOT_CRAN = "false"))
- [x] test with testthat 3e
- [x] devtools::check(remote=TRUE, cran=TRUE)
   - [x] macOS
   - [x] Ubuntu
- [x] win-builder
    - [x] devtools::check_win_devel()
    - [x] devtools::check_win_devel()
    - [x] devtools::check_win_old_release()
- [x] devtools::check() with valid "stage" environment token
- [x] `rhub::check_for_cran(email = "jclark@nceas.ucsb.edu", platforms = c("debian-gcc-devel", "fedora-clang-devel", "fedora-gcc-devel",  "macos-m1-bigsur-release", "macos-highsierra-release-cran", "windows-x86_64-devel", "windows-x86_64-release"))`
   - [ ] debian-gcc-devel (Debian Linux, R-devel) 
   - [x] fedora-clang-devel (Fedora Linux, R-devel, clang, gfortran)
   - [x] fedora-gcc-devel (Fedora Linux, R-devel, GCC)
   - [x] macos-m1-bigsur-release (Apple Silicon (M1), macOS 11.6 Big Sur, R-release)
   - [x] macos-highsierra-release-cran (macOS 10.13.6 High Sierra, R-release, CRAN's setup)
   - [x] windows-x86_64-devel (Windows Server 2008 R2 SP1, R-devel, 32/64 bit)
   - [x] windows-x86_64-release (Windows Server 2008 R2 SP1, R-release, 32/64 bit)
- [x] run spell_check()
- [x] merge develop into main
- [x] run devtools::release()
After release is posted by CRAN:
- [x] create release tag
- [x] update package revision (in 'develop' branch) to development version i.e. 2.2.2.9000

**Comment by jeanetteclark** [comment]
not running on Debian because of setup issues - for some reason its installing some packages from bioconductor?

**Comment by jeanetteclark** [comment]
@mbjones this is ready for review

**Comment by jeanetteclark** [comment]
re: rhub testing I got the following results

**Comment by jeanetteclark** [comment]
since the debian issue and the two windows issues seem specific to rhub I'm going to merge and release this
