### ISSUE TITLE
remove package hash from imports to avoid archival

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/rdataone#293]
CRAN notified us that we have until 2022-04-04 to remove the package `hash` from our imports to avoid archiving this package. Message from CRAN:

> Dear maintainers,
> 
> This concerns the CRAN/BioC packages
> 
>   BOG CITAN CRISPRseek CellNOptR GABi GUIDEseq GWASinspector GeneGA
>   IPDFileCheck Maaslin2 ReinforcementLearning STRINGdb TSDT TraRe
>   TrueSkillThroughTime coMET crisprseekplus dataone datapack epos hash
>   hhcartr medicalrisk nanotatoR neuroim noah orderbook packDAMipd
>   pkgndep popsom rFSA rankdist rgsepd ribor sBIC scPipe sklarsomega
>   tessellation tictactoe
> 
> maintained by one of you:
> ...
>   Matthew B. Jones <[jones@nceas.ucsb.edu](mailto:jones@nceas.ucsb.edu)>: dataone datapack
> ...
> 
> We have repeatedly asked for an update fixing the check problems
> shown on
>   <https://cran.r-project.org/web/checks/check_results_hash.html>
> with no reply from the maintainer thus far.
> 
> Thus, package hash is now scheduled for archival on 2022-04-04, and
> archiving this will necessitate also archiving its CRAN strong reverse
> dependencies.
> 
> Please negotiate the necessary actions.
> 
> Best
> -k

**Comment by mbjones** [comment]
Also note the same issue applies to `datapack`, and so we will need to release `dataone` with a new dependency on a new release of `datapack`.

**Comment by cboettig** [comment]
(minor comment but I believe R environments are already hash tables, which I believe is what `hash` used under the hood anyway)
