### ISSUE TITLE
Parse search results and expose in R data structure

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/rdataone#33]
The current search results in R are passed back to the user as raw XML. This may be useful for some users, but for many this will be a major impediment. Modify the search function to parse the results and create a data structure in R containing the search results. For example, maybe return a data frame indexed by identifier with one column for the identifier and for each of the returned fields in the resultset. Alternatively, one could return a vector containing, for each hit, a list containing the identifier and a hash of the returned fields for that identifier.

**Comment by sbpcs59** [comment]
D1Node:query(..., as="list") causes the solr query to be returned as a list, where each result
is a list element that contains a list of named values. For example, you could access the
title of the second result as:

```
list[[2]]$title
```

The query method calls D1Node:parseSolrResult to do this.

Query was updated in commit e530cd2f0015dd5444a418f131c14bc280fbcdd4

An upcoming vignette will give more complete examples.
