### ISSUE TITLE
Create DataPackage from ID of data or metadata file

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/rdataone#38]
Currently `DataPackage` instances can be created with the ID of the package of interest. However, users often have the ID of a metadata object or data object but not the ID of the package itself.  We shoudl provide methods in D1Client to get a DataPackage given the ID of one of its component data or metadata files. The difficult part of this is to determine which package to instantiate when an object is a member of multiple packages. One common case will be when there are multiple versions of a package due to edits in other files in the package; in this case, the best algorithm is probably to return the most recent revision in the package obsolescence chain that contains the id of interest. Other cases where an object is contained in multiple packages that are not in the same versioning chain are harder to decide on what to return.

**Comment by gothub** [comment]
`getDataPackage` now accepts the pid for a resource map, metadata object or data object and
gets the related package. Added in commit 7e4ca82a985e42155a92cc437049a2341ee71762
