### ISSUE TITLE
create unit test for pre-existing D1Object in createDataPackage

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/rdataone#39]
Ensure that `createDataPackage()` does not create a new object when trying to upload a package to a Member Node if that object already exists on DataONE.  The method currently checks `SystemMetadata` to see if the object already exists, and skips uploading it if it does.  But it needs to be tested.

**Comment by sbpcs59** [comment]
```uploadDataPackage``` which supercedes ```createDataPackage``` tests the SystemMetadata@dateUploaded slot to ensure that and object isn't uploaded if
it already has been. Implemented in commit 2bb9c72251ea05f453cc43b234944cceea796474
and added to tests in commit 21dd6a2a5b8e925d67a697c3e08eb1893e44cd79
