### ISSUE TITLE
Unable to create MNode instance with package:redland loaded

### ISSUE THREAD

**Issue by sbpcs59** [DataONEorg/rdataone#51]
There is a class name conflict between package:dataone Node and package:redland Node
as seen in the following R console log:

<pre>
<code>
> library(redland)
> library(dataone)
> mn_uri <- "https://dev.nceas.ucsb.edu/knb/d1/mn/v1"
> mn <- MNode(mn_uri)

 Error in stopifnot(!is.null(world)) :
  argument "world" is missing, with no default

Here is the traceback info:
8 stopifnot(!is.null(world)) at Node.R#51
7 .local(.Object, ...)
6 initialize(value, ...)
5 initialize(value, ...)
4 new("MNode")
3 new("MNode") at MNode.R#78
2 MNode(mn_uri) at MNode.R#71
1 MNode(mn_uri)

</code>
</pre>

Line 8 of the traceback shows a line from redland Node::initialize(). MNode inherits from dataone Node which does not have an initialize(), so it appears that what is happening is that the MNode superclass (Node) intialize() is trying to be called but the redland Node::initialize() is called instead.

One way to fix this is to rename dataone::Node to dataone::D1Node. 

I'm not sure if there is a
better wat to fix this such as options in setClass for dataone or redland Node, or to implement an
initialize function for dataone:Node class.

Any ideas on the best way to fix this?

**Comment by sbpcs59** [comment]
... and here is the formatted version of the output:

<pre>
<code>

&gt; library(redland)
&gt; library(dataone)
&gt; mn_uri &lt;- &quot;https://dev.nceas.ucsb.edu/knb/d1/mn/v1&quot;
&gt; mn &lt;- MNode(mn_uri)

 Error in stopifnot(!is.null(world)) :
  argument &quot;world&quot; is missing, with no default

  Traceback info:
8 stopifnot(!is.null(world)) at Node.R#51
7 .local(.Object, ...)
6 initialize(value, ...)
5 initialize(value, ...)
4 new(&quot;MNode&quot;)
3 new(&quot;MNode&quot;) at MNode.R#78
2 MNode(mn_uri) at MNode.R#71
1 MNode(mn_uri)

</code>
</pre>

**Comment by mbjones** [comment]
Node is a pretty generic name.  So not surprising that it conflicts.  Probably we should both provide an initialize method (even if it does nothing), and we could also rename the class.  The name `D1Node` would be fine.

**Comment by sbpcs59** [comment]
fixed in commit 02f0e5cea2b8c640049ce7c3144033263378a9e5
