### ISSUE TITLE
Update version number for version 2 release

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/rdataone#54]
The current released version number is 1.0.0.  The new development needs a beta release number, which due to R's version ordering, requires the new beta release to be in the 1.x major version series, so that later 2.0.0 can be released to CRAN properly.  So, set the versions as follows"

- [x] 1.1.0.9000 for the beta releases (increment 9000 for subsequent beta releases)
- [x] 2.0.0 when the final release is tagged

**Comment by gothub** [comment]
2.0.0 is the current version number, and the git repo will be tagged when accepted by CRAN
