### ISSUE TITLE
Write vignette for use of dataone package

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/rdataone#55]
We need a brief description of dataone package usage.  Probably base this on an example usage such as [@mbjones/upload-datasets](https://github.com/mbjones/upload-datasets).

**Comment by sbpcs59** [comment]
This vignette (or multiple vignettes) should include the following topics:

- session configuration using the SessionConfig class / methods
- searching for datasets in DataONE
- preparing and uploading metadata / data to DataONE

**Comment by mbjones** [comment]
@sbpcs59 and I discussed, and decided to create 3 vignettes:

- [ ] Overview of package, including:
    - basics of DataONE
    - reading data and metadata
    - data packaging, identifiers, and metadata (including sysmeta)
- [ ] Searching DataONE
- [ ] Writing / uploading to DataONE MNs, including:
    - authentication using CILogon

**Comment by sbpcs59** [comment]
The above mentioned vignettes have been added, and most recently edited in commit 8e836a81ef48a5a62a2006746e49becdbccd84e4
