### ISSUE TITLE
ensure backwards compatibility with 1.0.0

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/rdataone#56]
The current version of the `dataone` package renames a number of classes and functions for readability and generality.  Try to maintain backwards compatibility by providing classes and functions that delegate to their newer counterparts (and mark each as .Deprecated).  This includes:

- classes
    - [x] D1Object  -> DataObject
- functions
    - [x] D1Client::createD1Object -> upload
    - [x] D1Client::createDataPackage -> uploadPackage
    - [x] D1Client::getD1Object -> download
    - [x] D1Client::d1SolrQuery -> query
    - [x] D1Client::d1IdentifierSearch -> query
    - [x] D1Client::listMemberNodes -> ?? (pass through to CN.listNodes()?)

**Comment by sbpcs59** [comment]
All functions added as of commit adec721661c71b35f902891db8c82ffd9b532b9c

Need to add all of these methods to unit tests.

**Comment by sbpcs59** [comment]
Tests for all functions mentioned about have been added in commit f8b2a5f50083006ef702a5bfb4b8160d846b980f
