### ISSUE TITLE
set user agent header

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/rdataone#57]
The R client is currently reporting the user agent from curl.  The user agent string should be changed to reflect the name and version of the R client.  We can decide whether to include the curl agent string in the agent as well as the dataone package name.  Possibilities:

* r-dataone-2.0.0

Need to look up the typical user agent string format.

**Comment by sbpcs59** [comment]
User agents are covered in RFC 2616: http://www.ietf.org/rfc/rfc2616.txt , which allows for
multiple "product tokens" that include the "product name/version", in order of importance to the
software application making the request. An example from a user agent seen on KNB:
```
curl/7.41.0 Rcurl/1.95.4.5 httr/0.5
```

So we could have something like the following for the user agent string:

```
r-dataone/2.0.0 curl/7.41.0 Rcurl/1.95.4.5 httr/0.5
```

**Comment by vdave** [comment]
Note that 2616 is deprecated by 7231. The relevant section:

   http://tools.ietf.org/html/rfc7231#section-5.5.3

**Comment by mbjones** [comment]
@sbpcs59 Your proposal looks great.  Seems like we can just grab the UA string that would have been used by curl/rcurl/httr, and then prepend the r-dataone name and version as you did.  Perfect. Thanks.

Matt

**Comment by sbpcs59** [comment]
Added in commit c4898b54a5fe5182007e18e2ccc10015b8927ade

**Comment by sbpcs59** [comment]
The user agent sent to DataONE is currently set to "<r client version/R version", e.g.

```
"dataone/1.1.0.9006 R/3.2.2".
```
 Do we want to change it back to something like "<r-client-version httr-version curl-version libcurl-version>", e.g.

```
dataone/1.1.0.9006 httr/1.0 curl/0.6 libcurl/7.43.0
```

or something else? Note that httr no longer uses Rcurl, but uses the package 'curl' instead.

**Comment by sbpcs59** [comment]
The user agent string will be updated to the the format "dataone/<version> R/<version> httr/<version>",
for example:
```
dataone/2.0.0 R/3.2.2 httr/1.0.0
```
This user agent string only includes packages that the dataone R package is directly dependent on,
so no longer includes curl, which is a dependency of httr (httr dependencies may change in the future).
