### ISSUE TITLE
Add support for sending Authorization header with auth token

### ISSUE THREAD

**Issue by leinfelder** [DataONEorg/rdataone#62]

**Comment by sbpcs59** [comment]
Support for auth tokens added in commit 78f0a0c06be53fe1d307bc928e07f31dbc1fee3d.

Auth tokens are only sent if the node that will receive the request has v2 api (or higher), otherwise
certificates are used.

**Comment by sbpcs59** [comment]
Refactor CertificateManager to handle auth tokens. Only problem here is that the JSON Web Tokens package hasn't been implemented yet, so CertificateManager won't be able to decode auth tokens to determine the subject and expiration date. This will make isCertExpired, getCertExpires showClientSubject tricky for auth tokens at present. Also, not sure what to return for getCertLocation.

**Comment by sbpcs59** [comment]
Added a new class 'AuthenticationManager' that contains all the logic for checking tokens and certificates. This higher level class and the methods it provides simplifies accessing authentication.
This provides compatibility for DataONE v2 authentication tokens and does not replace CertficationManager.R, but instead using it for handling certificates.
