### ISSUE TITLE
refactor all functions to optionally require PKI

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/rdataone#68]
The PKI package is only needed for authentication, and the package should still be able to work if PKI is moved from Imports to Suggests.  The key is we need to check anytime we might need to make use of the PKI module. This will mainly affect CertificateManager, which should be refactored to detect when PKI is not present and then assert the public identity in all cases, possibly printing a warning that the PKI package needs to be installed to authenticate.

**Comment by leinfelder** [comment]
In the future, using an auth token will let you omit PKI, right?

**Comment by mbjones** [comment]
Yes, that is the case.  We will still need it to support use of CILogon certs, but the token will really simplify it.

**Comment by mbjones** [comment]
COmpleted refactor, which now depends on package PKIplus, which can be installed from github (NCEAS/PKIplus), or via drat on linux.
