### ISSUE TITLE
Move package to root directory

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/rdataone#76]
The `dataone` package is currently in a subdirectory of the repository at rdataone/dataone.  @sbpcs59 and I discussed options, and decided the best option is to move it to the top level, eliminating the "dataone" subdirectory, but maintaining the `dataone` package name.  This means that CRAN users will use `install.packages('dataone')`, but developers will use `devtools::install_github('rdataone')`.

**Comment by sbpcs59** [comment]
Done in commit 24b68969dbd9fe0fff12948b1c2f3eb00defb4ce
