### ISSUE TITLE
Remove PKIplus dependency?

### ISSUE THREAD

**Issue by sbpcs59** [DataONEorg/rdataone#82]
DataONE V2 will support authorization tokens. Do we need backward compatibility
for x509 certificates for any reason (they expire in 18 hours)? They do provide
a higher level of security (no man in the middle vunerability), but will we still support them?

**Comment by vdave** [comment]
Client certificates will continue to be supported as a mechanism for 
authentication.

They are essential for node interaction and when it gets right down to 
it, there are also ways to work with them in the workflow does not 
differ much from the token approach.

- Dave

**Comment by mbjones** [comment]
@sbpcs59 I agree with @vdave, we should support them until DataONE decides to drop them as a valid format. I expect most people will use the auth tokens because they are far easier to obtain.
