### ISSUE TITLE
Implement call to MN.getPackage() or local version?

### ISSUE THREAD

**Issue by sbpcs59** [DataONEorg/rdataone#87]
The MN.getPackage() is an optional service for member nodes, so should the R client
call this service or implement it's own service that does the equivalent, or both?

**Comment by mbjones** [comment]
For V2 nodes, call MN.getPackage, but for V1 nodes construct it ourselves.

**Comment by sbpcs59** [comment]
MNode.getPackage() was added in commit 125cd30adc6f49df0b1dfcbaa711f28559ae4ee1. This method
calls MN.getPackage and returns the filename of a bagit zip'd file located in a R session temporary
directory. 

To provide the ability to get packages from both v1 and v2 nodes, D1Client.getDataPackage will be
added, which calls MN.getPackage for a V2 node and builds a DataPackage object from it. For
V1 member nodes (that don't have MN.getPackage), each component of a D1 data package is downloaded individually and an R DataPackage is constructed from it.
This functionality is tracked in issue https://github.com/DataONEorg/rdataone/issues/83
