### ISSUE TITLE
Discontinue use of SessionConfig, use R options instead

### ISSUE THREAD

**Issue by sbpcs59** [DataONEorg/rdataone#95]
The R options facility performs the same function that the SessionConfig class and it's methods do, so
use it instead of SessionConfig.
The R options facility is a standard mechanism that is used by many packages and core R itself.
This facility is familiar to R uses and doesn't require learning a new mechanism to specify global
configuration options. All that is required is to document config params that must be entered
into the ~/.Rprofile startup file. Currently the dataone R package only uses "authentication_token"
parameter internally, and uses "subject_dn" in the tests (this will be discontinued when package is
available to get subject from authentication tokens).

**Comment by mbjones** [comment]
@sbpcs59 I suggest that you not require the user to enter all of the parameters.  The library should ship with sensibel defaults, and initialization code should set these options if the user hasn't set them from their .RProfile or otherwise.  It may also be useful to have a method to save all library-related options to .RProfile to make it easy for users to save their state.

**Comment by sbpcs59** [comment]
@mbjones Setting a set of parameters at package load time sounds fine, however, what would that 
default set be? The only parameter that is actually being used by dataone R package is the
'authentication_token', which is referenced inside a function and changes the behaviour of the package. All the other parameters are for potential use by packages that include dataone, e.g. recorder.

It may be confusing to set parameters via options() that don't actually affect the code. The dataone
package could set the parameters that it uses via .onLoad() and recordr will set the other parameters
that it uses/will use soon via .onLoad(): target_member_node_id, orcid_identifier, foaf_name, package_metadata_template_path, public_read_allowed, subject_dn, replication_allowed, number_of_replicas, preferred_replica_node_list, target_member_node_id, dataone_env

**Comment by mbjones** [comment]
@sbpcs59 yeah, of course, only set defaults that 1) are associated with the package in question, and 2) make sense. We obviously can't set a default auth token.

**Comment by sbpcs59** [comment]
AuthenticationManager.R is now checking for an auth token R option, "authentication_token"
The tests in inst/test are using the "subject_dn" for use in setting the rightsholder for uploaded data
as this is not available yet via auth tokens. The use of this parameter will be discontinued when
it is possible to read the subject from an auth token.

Implemented in commit b4d42c10d78d2b84d6220672a3542d0489ba7f20
